export type Skill = { name: string, stat: 'cha'|'wis'|'str'|'con'|'dex'|'int', proficent: boolean }
export const Skills: Skill[] = [
	{ name: "Athletics", stat: 'str', proficent: false },
	{ name: "Acrobatics", stat: 'dex', proficent: false },
	{ name: "Sleight of Hand", stat: 'dex', proficent: false },
	{ name: "Stealth", stat: 'dex', proficent: false },
	{ name: "Arcana", stat: 'int', proficent: false },
	{ name: "History", stat: 'int', proficent: false },
	{ name: "Investigation", stat: 'int', proficent: false },
	{ name: "Nature", stat: 'int', proficent: false },
	{ name: "Religion", stat: 'int', proficent: false },
	{ name: "Animal Handling", stat: 'wis', proficent: false },
	{ name: "Insight", stat: 'wis', proficent: false },
	{ name: "Medicine", stat: 'wis', proficent: false },
	{ name: "Perception", stat: 'wis', proficent: false },
	{ name: "Survival", stat: 'wis', proficent: false },
	{ name: "Deception", stat: 'cha', proficent: false },
	{ name: "Intimidation", stat: 'cha', proficent: false },
	{ name: "Performance", stat: 'cha', proficent: false },
	{ name: "Persuasion", stat: 'cha', proficent: false },
]